apiVersion: apps/v1
kind: StatefulSet     # I changed Deployment StatefulSet so that pods can have unique names as given by 'ServiceName', retain the names when there is a crash or deletion
metadata:
  name: train-schedule
spec:
  ServiceName: 'train-schedule-service' # ServiceName is required for Statefulset. TSS is means 'train-sechedule-service'
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: davidadeleke23/train-schedule:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: train-schedule
